Make `operator string_view` explicit
Otherwise clang++/libc++ chokes with:

    error: ambiguous conversion for static_cast from 'py::bytes' to 'std::string'

because it apparently has a `std::string(std::string_view)` constructor.